const file = `"""

DEBUG = False
DEBUG_PROPAGATE_EXCEPTIONS = False
USE_TZ = False
USE_I18N = True
LANGUAGE_COOKIE_SECURE = False
LANGUAGE_COOKIE_HTTPONLY = False
USE_L10N = False
EMAIL_USE_LOCALTIME = False
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
APPEND_SLASH = True
PREPEND_WWW = False
USE_THOUSAND_SEPARATOR = False
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_SSL_REDIRECT = False`;

console.log((file.match(new RegExp("True", "g")) || []).length);
